spring:
  application:
    name: account
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    create-schemas: true
    validate-migration-naming: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  private:
    key: 'classpath:app.key'
  public:
    key: 'classpath:app.pub'

